export type Logo = {
  id: number;
  name: string;
  alt: string;
  src: string;
};

// All logos from the public/images/logos folder
export const LOGOS: Logo[] = [
  { id: 1, name: "Logo_", alt: "Logo", src: "/images/logos/Logos_.webp" },
  { id: 2, name: "Logo_2", alt: "Logo 2", src: "/images/logos/Logos_2.webp" },
  { id: 3, name: "Logo_3", alt: "Logo 3", src: "/images/logos/Logos_3.webp" },
  { id: 4, name: "Logo_4", alt: "Logo 4", src: "/images/logos/Logos_4.webp" },
  { id: 5, name: "Logo_5", alt: "Logo 5", src: "/images/logos/Logos_5.webp" },
  { id: 6, name: "Logo_6", alt: "Logo 6", src: "/images/logos/Logos_6.webp" },
  { id: 7, name: "Logo_7", alt: "Logo 7", src: "/images/logos/Logos_7.webp" },
  { id: 8, name: "Logo_8", alt: "Logo 8", src: "/images/logos/Logos_8.webp" },
  { id: 9, name: "Logo_9", alt: "Logo 9", src: "/images/logos/Logos_9.webp" },
  {
    id: 10,
    name: "Logo_10",
    alt: "Logo 10",
    src: "/images/logos/Logos_10.webp",
  },
  {
    id: 11,
    name: "Logo_11",
    alt: "Logo 11",
    src: "/images/logos/Logos_11.webp",
  },
  {
    id: 12,
    name: "Logo_12",
    alt: "Logo 12",
    src: "/images/logos/Logos_12.webp",
  },
  {
    id: 13,
    name: "Logo_13",
    alt: "Logo 13",
    src: "/images/logos/Logos_13.webp",
  },
  {
    id: 14,
    name: "Logo_14",
    alt: "Logo 14",
    src: "/images/logos/Logos_14.webp",
  },
  {
    id: 15,
    name: "Logo_15",
    alt: "Logo 15",
    src: "/images/logos/Logos_15.webp",
  },
  {
    id: 16,
    name: "Logo_16",
    alt: "Logo 16",
    src: "/images/logos/Logos_16.webp",
  },
  {
    id: 17,
    name: "Logo_17",
    alt: "Logo 17",
    src: "/images/logos/Logos_17.webp",
  },
  {
    id: 18,
    name: "Logo_18",
    alt: "Logo 18",
    src: "/images/logos/Logos_18.webp",
  },
  {
    id: 19,
    name: "Logo_19",
    alt: "Logo 19",
    src: "/images/logos/Logos_19.webp",
  },
  {
    id: 20,
    name: "Logo_20",
    alt: "Logo 20",
    src: "/images/logos/Logos_20.webp",
  },
  {
    id: 21,
    name: "Logo_21",
    alt: "Logo 21",
    src: "/images/logos/Logos_21.png",
  },
  {
    id: 22,
    name: "Logo_22",
    alt: "Logo 22",
    src: "/images/logos/Logos_22.png",
  },
  {
    id: 23,
    name: "Logo_23",
    alt: "Logo 23",
    src: "/images/logos/Logos_23.png",
  },
  {
    id: 24,
    name: "Logo_24",
    alt: "Logo 24",
    src: "/images/logos/Logos_24.png",
  },
  {
    id: 25,
    name: "Logo_25",
    alt: "Logo 25",
    src: "/images/logos/Logos_25.png",
  },
  {
    id: 26,
    name: "Logo_26",
    alt: "Logo 26",
    src: "/images/logos/Logos_26.png",
  },
  {
    id: 27,
    name: "Logo_27",
    alt: "Logo 27",
    src: "/images/logos/Logos_27.png",
  },
  {
    id: 28,
    name: "Logo_28",
    alt: "Logo 28",
    src: "/images/logos/Logos_28.png",
  },
  {
    id: 29,
    name: "Logo_29",
    alt: "Logo 29",
    src: "/images/logos/Logos_29.png",
  },
  {
    id: 30,
    name: "Logo_30",
    alt: "Logo 30",
    src: "/images/logos/Logos_30.png",
  },
  {
    id: 31,
    name: "Logo_31",
    alt: "Logo 31",
    src: "/images/logos/Logos_31.png",
  },
  {
    id: 32,
    name: "Logo_32",
    alt: "Logo 32",
    src: "/images/logos/Logos_32.png",
  },
  {
    id: 33,
    name: "Logo_33",
    alt: "Logo 33",
    src: "/images/logos/Logos_33.png",
  },
  {
    id: 34,
    name: "Logo_34",
    alt: "Logo 34",
    src: "/images/logos/Logos_34.png",
  },
  {
    id: 35,
    name: "Logo_35",
    alt: "Logo 35",
    src: "/images/logos/Logos_35.png",
  },
  {
    id: 36,
    name: "Logo_36",
    alt: "Logo 36",
    src: "/images/logos/Logos_36.png",
  },
  {
    id: 37,
    name: "Logo_37",
    alt: "Logo 37",
    src: "/images/logos/Logos_37.png",
  },
  {
    id: 38,
    name: "Logo_38",
    alt: "Logo 38",
    src: "/images/logos/Logos_38.png",
  },
  {
    id: 39,
    name: "Logo_39",
    alt: "Logo 39",
    src: "/images/logos/Logos_39.png",
  },
  {
    id: 40,
    name: "Logo_40",
    alt: "Logo 40",
    src: "/images/logos/Logos_40.png",
  },
  {
    id: 41,
    name: "Logo_41",
    alt: "Logo 41",
    src: "/images/logos/Logos_41.png",
  },
  {
    id: 42,
    name: "Logo_42",
    alt: "Logo 42",
    src: "/images/logos/Logos_42.png",
  },
  {
    id: 43,
    name: "Logo_43",
    alt: "Logo 43",
    src: "/images/logos/Logos_43.png",
  },
  {
    id: 44,
    name: "Logo_44",
    alt: "Logo 44",
    src: "/images/logos/Logos_44.png",
  },
  {
    id: 45,
    name: "Logo_45",
    alt: "Logo 45",
    src: "/images/logos/Logos_45.png",
  },
  {
    id: 46,
    name: "Logo_46",
    alt: "Logo 46",
    src: "/images/logos/Logos_46.png",
  },
  {
    id: 47,
    name: "Logo_47",
    alt: "Logo 47",
    src: "/images/logos/Logos_47.png",
  },
  {
    id: 48,
    name: "Logo_48",
    alt: "Logo 48",
    src: "/images/logos/Logos_48.png",
  },
  {
    id: 49,
    name: "Logo_49",
    alt: "Logo 49",
    src: "/images/logos/Logos_49.png",
  },
  {
    id: 50,
    name: "Logo_50",
    alt: "Logo 50",
    src: "/images/logos/Logos_50.png",
  },
  {
    id: 51,
    name: "Logo_51",
    alt: "Logo 51",
    src: "/images/logos/Logos_51.png",
  },
  {
    id: 52,
    name: "Logo_52",
    alt: "Logo 52",
    src: "/images/logos/Logos_52.png",
  },
  {
    id: 53,
    name: "Logo_53",
    alt: "Logo 53",
    src: "/images/logos/Logos_53.png",
  },
  {
    id: 54,
    name: "Logo_54",
    alt: "Logo 54",
    src: "/images/logos/Logos_54.png",
  },
  {
    id: 55,
    name: "Logo_55",
    alt: "Logo 55",
    src: "/images/logos/Logos_55.png",
  },
  {
    id: 56,
    name: "Logo_56",
    alt: "Logo 56",
    src: "/images/logos/Logos_56.png",
  },
  {
    id: 57,
    name: "Logo_57",
    alt: "Logo 57",
    src: "/images/logos/Logos_57.png",
  },
  {
    id: 58,
    name: "Logo_58",
    alt: "Logo 58",
    src: "/images/logos/Logos_58.png",
  },
];
